apiVersion: v1
kind: PersistentVolume
metadata:
  name: ollama-pv-volume
  labels:
    type: local
spec:
  capacity:
    storage: 16Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    type: "DirectoryOrCreate"
    path: "/mnt/ollama"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 16Gi
