---
apiVersion: traefik.io/v1alpha1
kind: TraefikService
metadata:
  name: weighted-service
spec:
  weighted:
    services:
    - name: ollama
      namespace: ollama
      port: 11434
      weight: 1
