apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kepler
  namespace: kepler
spec:
  template:
    spec:
      runtimeClassName: "nvidia"
      containers:
      - name: kepler-exporter
        args:
          - -v=$(KEPLER_LOG_LEVEL)
          - -enable-gpu
