apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ollama
spec:
  values:
    ollama:
      gpu:
        enabled: false
      # -- List of models to pull at container startup
      models:
        pull:
          - gemma3:1b
