apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kepler
  namespace: kepler
spec:
  template:
    spec:
      runtimeClassName: "nvidia"
      containers:
      - args:
        - -v=5
        - -enable-gpu
