apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ollama-gpu
spec:
  releaseName: ollama-gpu
  chart:
    spec:
      chart: ollama
      sourceRef:
        kind: HelmRepository
        name: ollama-repo
        namespace: flux-system
  interval: 12h
  install:
    remediation:
      retries: 3
  values:
    ollama:
      gpu:
        enabled: true
        type: 'nvidia'
        number: 1
      # -- List of models to pull at container startup
      models:
        pull:
          - falcon:7b
          - mistral:7b
          - llama2:7b
          - llama3.2:1b
          - gemma3:1b
