---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-ollama
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-volumes
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/ollama/overlays/home
  prune: true
  timeout: 5m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-kepler
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/kepler/overlays/home
  prune: true
  timeout: 5m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-itpe-report
  namespace: flux-system
spec:
  interval: 1h
  dependsOn:
    - name: app-ollama
    - name: manifests-metallb
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/itpe-report/overlays/home
  prune: true
  timeout: 5m0s
