apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gpu-operator
  namespace: gpu-operator
spec:
  releaseName: gpu-operator
  chart:
    spec:
      chart: gpu-operator
      sourceRef:
        kind: HelmRepository
        name: nvidia-repo
        namespace: flux-system
  interval: 12h
  install:
    remediation:
      retries: 3
  values:
    version: "v25.3.2"
