apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kepler-old
spec:
  releaseName: kepler-old
  chart:
    spec:
      chart: kepler
      sourceRef:
        kind: HelmRepository
        name: kepler-old-repo
  interval: 1h
  values:
    image:
      tag: "release-0.9"
    serviceMonitor:
      enabled: true
      interval: 5s
      labels:
        release: prometheus
